version: '3.6'
services:

  app:
    build:
      args:
      # replace with your user and uid
        user: rahman
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    image: laravel-8-booking:latest
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - proxynet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    working_dir: /var/www/html
    volumes:
        - .:/var/www/html
        - ./docker/nginx/log:/var/log/nginx
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8000:80
    networks:
      - proxynet
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - 8040:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes: 
      - ./docker/db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - proxynet

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    depends_on:
      - db
    ports:
      - 8030:8080
    networks:
      - proxynet

volumes:
  mysql_data:

networks:
  proxynet:
    name: mynet
    driver: bridge